fix undefined var 'user'
when a user, group is defined in diamond.conf,
we end up with the below error,

 ERROR: Failed to set UID/GID. global name 'user' is not defined